# Generated by Django 5.2 on 2025-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretariaEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_secretaria', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email da Secretaria',
                'verbose_name_plural': 'Emails das Secretarias',
            },
        ),
        migrations.CreateModel(
            name='StatusSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status da Solicitação',
                'verbose_name_plural': 'Status das Solicitações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AssuntoReclamacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('emails_secretaria', models.ManyToManyField(to='contact.secretariaemail')),
            ],
            options={
                'verbose_name': 'Assunto da Reclamação',
                'verbose_name_plural': 'Assuntos da Reclamação',
            },
        ),
    ]
